# Generated by Django 6.0.7 on 2026-07-23 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstituencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('submitter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('submitter_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('translation', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('source_language', models.CharField(default='en', max_length=20)),
                ('constituency', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('ROADS', 'Roads & Transport'), ('WATER', 'Water Supply'), ('ELECTRICITY', 'Electricity & Power'), ('HEALTH', 'Healthcare & Sanitation'), ('EDUCATION', 'Education & Schools'), ('FINANCIAL_AID', 'Financial Aid'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('urgency', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated')], default='PENDING', max_length=20)),
                ('voice_file', models.FileField(blank=True, null=True, upload_to='voice_requests/')),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='requests_app.constituencyrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MLA', 'MLA'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('constituency', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
