# Generated by Django 6.0.7 on 2026-08-06 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_appointments', models.IntegerField(default=3)),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConstituencyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ROADS', 'Roads & Transport'), ('WATER', 'Water Supply'), ('ELECTRICITY', 'Electricity & Power'), ('HEALTH', 'Healthcare & Sanitation'), ('EDUCATION', 'Education & Schools'), ('FINANCIAL_AID', 'Financial Aid'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spent_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('resolution_time_days', models.IntegerField(default=14)),
                ('description', models.TextField(blank=True, null=True)),
                ('financial_year', models.CharField(default='2025-2026', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='constituencyrequest',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='requests_app.constituencyrequest'),
        ),
        migrations.AddField(
            model_name='constituencyrequest',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='constituencyrequest',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='constituencyrequest',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('MLA', 'MLA'), ('STAFF', 'Staff'), ('CITIZEN', 'Citizen')], default='CITIZEN', max_length=20),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_name', models.CharField(max_length=100)),
                ('citizen_phone', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='BOOKED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='requests_app.appointmentslot')),
            ],
        ),
    ]
