# Generated by Django 6.0.7 on 2026-08-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_appointmentslot_constituencybudget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituencybudget',
            name='constituency',
            field=models.CharField(default='Aluva', max_length=100),
        ),
    ]
