# Generated by Django 5.2.17 on 2026-08-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_constituencybudget_constituency'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituencyrequest',
            name='custom_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
